services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-runtime
    environment:
      - SERVER_PORT=55833
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", "55833"]
      interval: 5s
      timeout: 10s
      retries: 5

  client:
    scale: 2
    build:
      context: .
      dockerfile: Dockerfile
      target: client-runtime
    depends_on:
      server:
        condition: service_healthy
    environment:
      - SERVER_PORT=55833
      - SERVER_NAME=server